version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:

### twemproxy ################################################
    twemproxy:
      build: ./gcc
      tty: true
      volumes:
        - ./twemproxy/conf:/usr/local/sbin/twemproxy/conf
        - ./twemproxy/log:/usr/local/sbin/twemproxy/log
      networks:
        - backend

### Redis First ################################################
    redis_first:
      build: ./redis_first
      ports:
        - "${REDIS_FIRST_PORT}:6379"
      networks:
        - backend

### Redis Second ################################################
    redis_second:
      build: ./redis_second
      ports:
        - "${REDIS_SECOND_PORT}:6379"
      networks:
        - backend

### Redis Third ################################################
    redis_third:
      build: ./redis_third
      ports:
        - "${REDIS_THIRD_PORT}:6379"
      networks:
        - backend